added book entity , book repo
chertterner/bookShop pull request #1
Opened 2023-09-29 12:56 UTC by chertterner

2023-09-29 14:03 UTC, sokimaaa commented on src/main/java/com/example/bookshop/BookShopApplication.java
> +    }
```suggestion
 
    public static void main(String[] args) {
        SpringApplication.run(BookShopApplication.class, args);
    }

    @Bean
    public CommandLineRunner commandLineRunner(BookService bookService) {
        return args -> {
            Book book = new Book();
            book.setDescription(" ");
            book.setIsbn(" ");
            book.setPrice(BigDecimal.ONE);
            book.setTitle(" ");
            book.setAuthor(" ");

            bookService.save(book);
            System.out.println(bookService.findAll());
        };
    }
```

2023-09-29 14:04 UTC, sokimaaa commented on src/main/java/com/example/bookshop/model/Book.java
> +@Data
Using @Data in conjunction with @Entity is not recommended.

2023-09-29 14:06 UTC, sokimaaa commented on src/main/java/com/example/bookshop/model/Book.java
> +    private String coverImage;
I see any constraints requested by the task, e.g. not null, unique

2023-09-29 14:10 UTC, sokimaaa commented on src/main/java/com/example/bookshop/repository/implementation/BookRepositoryImpl.java
> +    @Transactional
use one of the methods to reach the transaction (not both!).
1) using @Transactional
2) using SessionFactory#beginTransaction and its methods

2023-10-01 09:08 UTC, aaananas approved these changes

2023-10-04 17:57 UTC, kerrrusha requested changes
java ci checks failed

2023-10-05 13:52 UTC, merged