added ShoppingCart
chertterner/bookShop pull request #10
Opened 2024-12-08 18:24 UTC by chertterner

2024-12-09 19:59 UTC, Elena-Bruyako requested changes
see comments

2024-12-09 19:59 UTC, Elena-Bruyako commented on src/main/java/com/example/bookshop/controller/ShoppingCartController.java
> +    public void addBookShoppingCart(
```suggestion
    public ShoppingCartDto addBookShoppingCart(
```

2024-12-09 19:59 UTC, Elena-Bruyako commented on src/main/java/com/example/bookshop/controller/ShoppingCartController.java
> +    public void updateCategory(@PathVariable Long id,
rename method
```suggestion
    public ShoppingCartDto updateCategory(@PathVariable Long id,
```

2024-12-09 19:59 UTC, Elena-Bruyako commented on src/main/java/com/example/bookshop/dto/AddBookShoppingCartRequestDto.java
> +public class AddBookShoppingCartRequestDto {
```suggestion
public class CartItemRequestDto {
```

2024-12-09 19:59 UTC, Elena-Bruyako commented on src/main/java/com/example/bookshop/dto/AddBookShoppingCartRequestDto.java
> +    private long bookId;
```suggestion
    private Long bookId;
```

2024-12-09 19:59 UTC, Elena-Bruyako commented on src/main/java/com/example/bookshop/dto/AddBookShoppingCartRequestDto.java
> +    private long bookId;
add validation for bookId and quantity

2024-12-09 19:59 UTC, Elena-Bruyako commented on src/main/java/com/example/bookshop/dto/BookQuantityReqDto.java
> +public class BookQuantityReqDto {
```suggestion
public class UpdateCartItemDto {
```

2024-12-09 19:59 UTC, Elena-Bruyako commented on src/main/java/com/example/bookshop/dto/BookQuantityReqDto.java
> +    private int quantity;
add validation

2024-12-09 19:59 UTC, Elena-Bruyako commented on src/main/java/com/example/bookshop/model/Book.java
> +    @OneToOne
```suggestion
    @OneToOne(fetch = FetchType.LAZY)
```

2024-12-09 19:59 UTC, Elena-Bruyako commented on src/main/java/com/example/bookshop/model/CartItem.java
> +    @ManyToOne
```suggestion
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
```

2024-12-09 19:59 UTC, Elena-Bruyako commented on src/main/java/com/example/bookshop/model/CartItem.java
> +    @OneToOne
add Lazy and JoinColumn

2024-12-09 19:59 UTC, Elena-Bruyako commented on src/main/java/com/example/bookshop/model/CartItem.java
> +    @NotNull
```suggestion
```

2024-12-09 19:59 UTC, Elena-Bruyako commented on src/main/java/com/example/bookshop/model/ShoppingCart.java
> +    private Set<CartItem> cartItems;
```suggestion
    private Set<CartItem> cartItems = new HashSet<>();
```

2024-12-09 19:59 UTC, Elena-Bruyako commented on src/main/java/com/example/bookshop/model/ShoppingCart.java
> +    @NotNull
```suggestion
```

2024-12-09 19:59 UTC, Elena-Bruyako commented on src/main/java/com/example/bookshop/model/ShoppingCart.java
> +    @OneToOne
you can use @MapsId here 
```suggestion
    @OneToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id", nullable = false)
```

2024-12-09 19:59 UTC, Elena-Bruyako commented on src/main/java/com/example/bookshop/model/User.java
> +    private ShoppingCart shoppingCart;
remove

2024-12-09 19:59 UTC, Elena-Bruyako commented on src/main/java/com/example/bookshop/service/implementation/ShoppingCartImpl.java
> +@RequiredArgsConstructor
Think where `@Transactional` is needed

2024-12-09 19:59 UTC, Elena-Bruyako commented on src/main/java/com/example/bookshop/model/ShoppingCart.java
> +    @OneToMany
```suggestion
    @OneToMany(mappedBy = "shoppingCart", cascade = CascadeType.ALL, orphanRemoval = true)
```

2024-12-09 19:59 UTC, Elena-Bruyako commented on src/main/java/com/example/bookshop/service/implementation/ShoppingCartImpl.java
> +        CartItem cartItem = new CartItem();
find shop cart by id, check if cartItems in shop cart already include this book,  add book, save shop cart to db

2024-12-09 19:59 UTC, Elena-Bruyako commented on src/main/java/com/example/bookshop/service/implementation/ShoppingCartImpl.java
> +        User user = getCurrentUser(userDetails);
let's find shop cart by userId
find cartitem `findByIdAndShoppingCartId`
update quantity 
save cartItem

2024-12-09 19:59 UTC, Elena-Bruyako commented on src/main/java/com/example/bookshop/service/implementation/ShoppingCartImpl.java
> +        User user = getCurrentUser(userDetails);
same here
find shop cart by userId
find cart item `findByIdAndShoppingCartId`
remove

2024-12-12 16:09 UTC, Elena-Bruyako requested changes
see comments

2024-12-12 16:09 UTC, Elena-Bruyako commented on src/main/java/com/example/bookshop/dto/CartItemRequestDto.java
> +    @Length(min = 1)
```suggestion
    @NotNull
    @Positive
    private Long bookId;
    @Positive
```

2024-12-12 16:09 UTC, Elena-Bruyako commented on src/main/java/com/example/bookshop/dto/UpdateCartItemDto.java
> +    @Length(min = 1)
```suggestion
    @Positive
```

2024-12-12 16:09 UTC, Elena-Bruyako commented on src/main/java/com/example/bookshop/model/Book.java
> +    private CartItem cartItem;
```suggestion
    @OneToMany(mappedBy = "book", cascade = CascadeType.REMOVE, orphanRemoval = true)
    private List<CartItem> cartItems = new ArrayList<>();
```

2024-12-12 16:09 UTC, Elena-Bruyako commented on src/main/java/com/example/bookshop/model/ShoppingCart.java
> +@Table(name = "shopping_cart")
table name should be plural
```suggestion
@Table(name = "shopping_carts")
```

2024-12-12 16:09 UTC, Elena-Bruyako commented on src/main/java/com/example/bookshop/service/implementation/ShoppingCartImpl.java
> +public class ShoppingCartImpl implements ShoppingCartService {
```suggestion
public class ShoppingCartServiceImpl implements ShoppingCartService {
```

2024-12-12 16:09 UTC, Elena-Bruyako commented on src/main/java/com/example/bookshop/service/implementation/ShoppingCartImpl.java
> +    private User getCurrentUser(UserDetails userDetails) {
you can provide Authentication to endpoints and get User from Principal and find user by id

2024-12-15 12:43 UTC, Elena-Bruyako requested changes
see comments

2024-12-15 12:43 UTC, Elena-Bruyako commented on src/main/java/com/example/bookshop/dto/cartitem/CartItemDto.java
> +public class CartItemDto {
Do you use this DTO?

2024-12-15 12:43 UTC, Elena-Bruyako commented on src/main/java/com/example/bookshop/dto/cartitem/ShoppingCartDto.java
> +    @NotNull
don't need to validate response

2024-12-15 12:43 UTC, Elena-Bruyako commented on src/main/java/com/example/bookshop/model/ShoppingCart.java
> +    @OneToOne(fetch = FetchType.LAZY)
you can use `@MapsId` here

2024-12-15 12:43 UTC, Elena-Bruyako commented on src/main/java/com/example/bookshop/model/ShoppingCart.java
> +}
do we need soft delete approach here?

2024-12-15 12:43 UTC, Elena-Bruyako commented on src/main/java/com/example/bookshop/service/implementation/ShoppingCartServiceImpl.java
> +        Optional<CartItem> cartItem = Optional.ofNullable(
just `shoppingCart.getCartItems()`

2024-12-15 12:43 UTC, Elena-Bruyako commented on src/main/java/com/example/bookshop/service/implementation/ShoppingCartServiceImpl.java
> +
let's create shoppingCart when user registers. Create method in `ShoppingCartService` and use it `UserService`

2024-12-16 21:00 UTC, sarakhmen approved these changes

2024-12-22 06:13 UTC, merged