added Order
chertterner/bookShop pull request #11
Opened 2024-12-22 17:22 UTC by chertterner

2024-12-22 18:35 UTC, Elena-Bruyako requested changes
see comments

2024-12-22 18:35 UTC, Elena-Bruyako commented on src/main/java/com/example/bookshop/dto/order/ShippingAddressRequestDto.java
> +    @NotNull
```suggestion
    @NotBlank
```

2024-12-22 18:35 UTC, Elena-Bruyako commented on src/main/java/com/example/bookshop/dto/order/UpdateStatusDto.java
> +    @NotNull
```suggestion
    @NotBlank
```

2024-12-22 18:35 UTC, Elena-Bruyako commented on src/main/java/com/example/bookshop/model/Order.java
> +    @NotNull
```suggestion
```

2024-12-22 18:35 UTC, Elena-Bruyako commented on src/main/java/com/example/bookshop/model/OrderItem.java
> +    @NotNull
```suggestion
```

2024-12-22 18:35 UTC, Elena-Bruyako commented on src/main/java/com/example/bookshop/model/OrderItem.java
> +    @NotNull
```suggestion
```

2024-12-22 18:35 UTC, Elena-Bruyako commented on src/main/java/com/example/bookshop/service/implementation/OrderServiceImpl.java
> +        if (order == null) {
let's use Optional instead if checking null

2024-12-22 18:35 UTC, Elena-Bruyako commented on src/main/java/com/example/bookshop/service/implementation/OrderServiceImpl.java
> +        Order order = orderRepository.findByUser_Id(user.getId());
find shop cart by user id, check if cartItems is not empty, create order and clear shop cart

2024-12-22 18:35 UTC, Elena-Bruyako commented on src/main/java/com/example/bookshop/service/implementation/OrderServiceImpl.java
> +        Optional<Order> order = orderRepository.findById(id);
```suggestion
        Order order = orderRepository.findById(id).orElseThrow(() -> new EntityNotFoundException(....
```

2024-12-22 18:35 UTC, Elena-Bruyako commented on src/main/java/com/example/bookshop/service/implementation/OrderServiceImpl.java
> +        return new PageImpl<>(orderRepository.findById(id)
use `findByIdAndOrderIdAndUserId` fo find orderItem

2024-12-22 18:35 UTC, Elena-Bruyako commented on src/main/java/com/example/bookshop/service/implementation/OrderServiceImpl.java
> +        return new PageImpl<>(orderRepository.findById(id)
use `findByIdAndUserId` to find order and get orderItems

2024-12-22 18:35 UTC, Elena-Bruyako commented on src/main/resources/db/changelog/changes/insert-order-item.yaml
> +  - changeSet:
remove

2024-12-22 18:35 UTC, Elena-Bruyako commented on src/main/resources/db/changelog/changes/insert-order.yaml
> +      id: 0
remove

2025-01-02 08:41 UTC, liliia-ponomarenko requested changes
Good job! Let’s improve your solution ;)

2025-01-02 08:41 UTC, liliia-ponomarenko commented on src/main/java/com/example/bookshop/dto/order/UpdateStatusDto.java
> +    @NotBlank
```suggestion
    @NotNull
```
Because Status is an object

2025-01-02 08:41 UTC, liliia-ponomarenko commented on src/main/java/com/example/bookshop/model/Order.java
> +    private String shippingAddress;
you already validate dto on java level here you should validate the object on the DB level (use `Column(nullable=false)`)

2025-01-02 08:41 UTC, liliia-ponomarenko commented on src/main/java/com/example/bookshop/model/OrderItem.java
> +    private int quantity;
primitive type can’t be null

2025-01-02 08:41 UTC, liliia-ponomarenko commented on src/main/java/com/example/bookshop/model/OrderItem.java
> +    @NotNull
the same, use Column annotation

2025-01-02 08:41 UTC, liliia-ponomarenko commented on src/main/java/com/example/bookshop/repository/OrderRepository.java
> +    Optional<Order> findByUser_Id(Long userId);
```suggestion
    Optional<Order> findByUserId(Long userId);
```

2025-01-02 08:41 UTC, liliia-ponomarenko commented on src/main/java/com/example/bookshop/repository/OrderRepository.java
> +    Optional<Order> findByIdAndUser_Id(Long id, Long userId);
```suggestion
    Optional<Order> findByIdAndUserId(Long id, Long userId);
```

2025-01-02 08:41 UTC, liliia-ponomarenko commented on src/main/java/com/example/bookshop/service/implementation/OrderServiceImpl.java
> +        return new PageImpl<>(orderRepository.findAll(pageable)
Create custom repository method `Page<Order> findAll(Pageble pageble);` and use method `map` of Page

2025-01-02 08:41 UTC, liliia-ponomarenko commented on src/main/java/com/example/bookshop/service/implementation/OrderServiceImpl.java
> +        ShoppingCart shoppingCart = shoppingCartRepository.findShoppingCartByUser_Id(user.getId());
```suggestion
        ShoppingCart shoppingCart = shoppingCartRepository.findShoppingCartByUserId(user.getId());
```
Don’t use snake case in the repository methods

2025-01-02 08:41 UTC, liliia-ponomarenko commented on src/main/java/com/example/bookshop/service/implementation/OrderServiceImpl.java
> +            throw new EntityNotFoundException("There is empty shopping cart!");
better create another custom exception OrderProcessingException for example

2025-01-02 08:41 UTC, liliia-ponomarenko commented on src/main/java/com/example/bookshop/service/implementation/OrderServiceImpl.java
> +        }
Let’s  use orElseThrow instead

2025-01-02 08:41 UTC, liliia-ponomarenko commented on src/main/java/com/example/bookshop/service/implementation/OrderServiceImpl.java
> +                .toList());
the same issue

2025-01-02 08:41 UTC, liliia-ponomarenko commented on src/main/java/com/example/bookshop/service/implementation/OrderServiceImpl.java
> +        return new PageImpl<>(orderRepository.findByIdAndUser_Id(orderId, user.getId())
the same

2025-01-02 08:41 UTC, liliia-ponomarenko commented on src/main/resources/db/changelog/changes/create-order.yaml
> +                    nullable: false
do you need this column?

2025-01-02 08:41 UTC, liliia-ponomarenko commented on src/main/resources/db/changelog/db.changelog-master.yaml
> +      file: db/changelog/changes/create-order-item.yaml
Better include it at the end

2025-01-03 08:20 UTC, liliia-ponomarenko requested changes
Good job! Let’s fix the comments ;)

2025-01-03 08:20 UTC, liliia-ponomarenko commented on src/main/java/com/example/bookshop/repository/CartItemRepository.java
> +    CartItem findByBook_IdAndShoppingCartId(Long bookId, Long shoppingCartId);
```suggestion
    CartItem findByBookIdAndShoppingCartId(Long bookId, Long shoppingCartId);
```

2025-01-03 08:20 UTC, liliia-ponomarenko commented on src/main/java/com/example/bookshop/repository/OrderRepository.java
> +
```suggestion
    Optional<Order> findByUserId(Long userId);

    Optional<Order> findByIdAndUserId(Long id, Long userId);
```

2025-01-03 08:20 UTC, liliia-ponomarenko commented on src/main/java/com/example/bookshop/service/implementation/OrderServiceImpl.java
> +            throw new OrderProcessingException("There is empty shopping cart!");
better add some parameter to the message for example shopping cart id

2025-01-03 08:20 UTC, liliia-ponomarenko commented on src/main/java/com/example/bookshop/service/implementation/OrderServiceImpl.java
> +        Optional<Order> order = Optional.ofNullable(
And how should the order appear in the database? You need to convert the user's shopping cart to an order. Don’t forget to clear the user's shopping cart.

2025-01-03 08:20 UTC, liliia-ponomarenko commented on src/main/java/com/example/bookshop/service/implementation/OrderServiceImpl.java
> +        Order order = orderRepository.findByIdAndUserId(id, user.getId())
you should pass Pageable to the repository method. Return Page<OrderItem> and use the method map of Page

2025-01-03 08:20 UTC, liliia-ponomarenko commented on src/main/java/com/example/bookshop/service/implementation/OrderServiceImpl.java
> +    public Page<OrderItemDto> findSpecificOrderItem(Long orderId,
Why do you return Page here?

2025-01-03 08:20 UTC, liliia-ponomarenko commented on src/main/resources/db/changelog/changes/create-order-item.yaml
> +                    nullable: false
add FK constraint

2025-01-03 08:20 UTC, liliia-ponomarenko commented on src/main/resources/db/changelog/changes/create-order.yaml
> +                    nullable: false
the same

2025-01-04 12:18 UTC, Elena-Bruyako requested changes
see comments

2025-01-04 12:18 UTC, Elena-Bruyako commented on src/main/java/com/example/bookshop/controller/OrderController.java
> +                                              @RequestBody UpdateStatusDto updateStatusDto) {
```suggestion
                                              @RequestBody @Valid UpdateStatusDto updateStatusDto) {
```

2025-01-04 12:18 UTC, Elena-Bruyako commented on src/main/java/com/example/bookshop/dto/order/ShippingAddressRequestDto.java
> +public class ShippingAddressRequestDto {
rename

2025-01-04 12:18 UTC, Elena-Bruyako commented on src/main/java/com/example/bookshop/service/implementation/OrderServiceImpl.java
> +        Order order = new Order();
let's divide this logic to separate methods

2025-01-06 18:46 UTC, Elena-Bruyako approved these changes

2025-01-08 15:28 UTC, merged