added User model and authentication/login controller
chertterner/bookShop pull request #6
Opened 2023-12-14 10:53 UTC by chertterner

2023-12-14 12:55 UTC, Sanderfuck requested changes

2023-12-14 12:55 UTC, Sanderfuck commented on src/main/java/com/example/bookshop/annotation/FieldMatch.java
> +    }
For what it is?

2023-12-14 12:55 UTC, Sanderfuck commented on src/main/java/com/example/bookshop/model/User.java
> +    }
You can use lombok instead of this

2023-12-14 12:55 UTC, Sanderfuck commented on src/main/java/com/example/bookshop/validators/FieldMatchValidator.java
> +
```suggestion
```

2023-12-14 12:55 UTC, Sanderfuck commented on src/main/java/com/example/bookshop/validators/FieldMatchValidator.java
> +            // ignore
What is it?

2023-12-15 09:44 UTC, Rommelua requested changes

2023-12-15 09:44 UTC, Rommelua commented on src/main/java/com/example/bookshop/annotation/FieldMatch.java
> +package com.example.bookshop.annotation;
```suggestion
package com.example.bookshop.validator;
```

2023-12-15 09:44 UTC, Rommelua commented on src/main/java/com/example/bookshop/controllers/AuthenticationController.java
> +package com.example.bookshop.controllers;
```suggestion
package com.example.bookshop.controller;
```

2023-12-15 09:44 UTC, Rommelua commented on src/main/java/com/example/bookshop/controllers/AuthenticationController.java
> +        return authenticationService.login(request);
![image](https://github.com/chertterner/bookShop/assets/20326858/b36d848d-d8da-4f81-85ab-b4bcd81e3cce)

2023-12-15 09:44 UTC, Rommelua commented on src/main/java/com/example/bookshop/exceptions/RegistrationException.java
> +package com.example.bookshop.exceptions;
```suggestion
package com.example.bookshop.exception;
```

2023-12-15 09:44 UTC, Rommelua commented on src/main/java/com/example/bookshop/mappers/UserMapper.java
> +package com.example.bookshop.mappers;
```suggestion
package com.example.bookshop.mapper;
```

2023-12-15 09:44 UTC, Rommelua commented on src/main/java/com/example/bookshop/validators/FieldMatchValidator.java
> +package com.example.bookshop.validators;
```suggestion
package com.example.bookshop.validator;
```

2023-12-19 09:33 UTC, Rommelua approved these changes

2023-12-19 15:04 UTC, merged